
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nn"
version = "0.1.0"
description = "Neural network implementations"
requires-python = ">=3.8"

dependencies = [
"mlxtend",
"numpy",
"matplotlib"
]
